export const objectsList = [
  {
    id: 111,
    price: 1,
    city: "zemun",
    img: "./img/objekti/crveni_rak.jpg",
    name: "test 1",
    info: "Adresa: Beogradska 14, Zemun",
    fb: "https://www.facebook.com/CrveniRak/?ref=br_rs",
    facilities: { petFriendly: true, liveMusic: true, food: true, wifi: true },
    lat: 44.844527,
    lng: 20.4161,
  },
  {
    id: 112,
    price: 1,
    city: "zemun",
    img: "./img/objekti/crveni_rak.jpg",
    name: "test 2",
    info: "Adresa: Beogradska 14, Zemun",
    fb: "https://www.facebook.com/CrveniRak/?ref=br_rs",
    facilities: {
      petFriendly: false,
      liveMusic: false,
      food: false,
      wifi: false,
    },
  },
  {
    id: 1,
    price: 1,
    city: "zemun",
    img: "./img/objekti/crveni_rak.jpg",
    name: "crveni rak",
    info: "Adresa: Beogradska 14, Zemun",
    fb: "https://www.facebook.com/CrveniRak/?ref=br_rs",
    facilities: { petFriendly: true, liveMusic: true, food: true, wifi: true },
  },
  {
    id: 2,
    price: 31,
    city: "zemun",
    img: "./img/objekti/crni_mata_pub.jpg",
    name: "crni mata pub",
    info:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: {
      petFriendly: true,
      liveMusic: true,
      food: false,
      wifi: false,
    },
    lat: 44.847219,
    lng: 20.411037,
  },
  {
    id: 3,
    price: 1,
    city: "zemun",
    img: "./img/objekti/cirkus_pab.jpg",
    name: "cirkus pab",
    info:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: {
      petFriendly: true,
      liveMusic: true,
      food: false,
      wifi: false,
    },
    lat: 44.839526,
    lng: 20.407919,
  },
  {
    id: 4,
    price: 1,
    city: "zemun",
    img: "./img/objekti/fat_cat.jpg",
    name: "fat cat",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false, wifi: true },
    lat: 44.848434,
    lng: 20.409961,
  },
  {
    id: 5,
    price: 1,
    city: "zemun",
    img: "./img/objekti/fest.jpg",
    name: "klub fest",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false, wifi: true },
    lat: 44.840364,
    lng: 20.410921,
  },
  {
    id: 6,
    price: 1,
    city: "zemun",
    img: "./img/objekti/taurunum_pub.jpg",
    name: "taurunum pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: true, wifi: false },
    lat: 44.844397,
    lng: 20.408082,
  },
  {
    id: 7,
    price: 1,
    city: "zemun",
    img: "./img/objekti/lager_pub.jpg",
    name: "lager pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false, wifi: true },
    lat: 44.846571,
    lng: 20.40639,
  },
  {
    id: 8,
    price: 4,
    city: "zemun",
    img: "./img/objekti/office_pub.jpg",
    name: "office pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: true, wifi: true },
    lat: 44.83297,
    lng: 20.421015,
  },
  {
    id: 9,
    price: 4,
    city: "dorcol",
    img: "./img/objekti/gvint.jpg",
    name: "gvint",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: true, wifi: true },
    lat: 44.823136,
    lng: 20.467767,
  },
  {
    id: 10,
    price: 4,
    city: "beograd",
    img: "./img/objekti/ciglaBG.jpg",
    name: "Cigla",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false, wifi: true },
    lat: 44.817878,
    lng: 20.458624,
  },
  {
    id: 11,
    price: 4,
    city: "zemun",
    img: "./img/objekti/prviMaj.jpg",
    name: "prvi maj",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false, wifi: true },
    lat: 44.841716,
    lng: 20.393879,
  },
  {
    id: 12,
    price: 4,
    city: "Novi Beograd",
    img: "./img/objekti/zirafaNBG.jpg",
    name: "žirafa",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false, wifi: true },
    lat: 44.806789,
    lng: 20.424501,
  },
  {
    id: 13,
    price: 4,
    city: "Niš",
    img: "./img/objekti/minisNI.jpg",
    name: "Ministarstvo pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false, wifi: true },
  },
  {
    id: 14,
    price: 4,
    city: "Beograd",
    img: "./img/objekti/gvo.jpg",
    name: "Gvožđara 1870",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
    lat: 44.804895,
    lng: 20.447588,
  },
  {
    id: 15,
    price: 4,
    city: "Subotica",
    img: "./img/objekti/samoSU.jpg",
    name: "Samo pivo",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: false, food: true },
    lat: 46.099316,
    lng: 19.663647,
  },
  {
    id: 16,
    price: 4,
    city: "Subotica",
    img: "./img/objekti/livpoolSU.jpg",
    name: "Liverpool pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
    lat: 46.098568,
    lng: 19.662856,
  },
  {
    id: 17,
    price: 4,
    city: "niš",
    img: "./img/objekti/beergardenNI.jpg",
    name: "Beergarden",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: false, liveMusic: true, food: false },
  },
  {
    id: 18,
    price: 4,
    city: "Novi sad",
    img: "./img/objekti/gradskaNS.jpg",
    name: "Gradska pivnica",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: false, liveMusic: true, food: false },
  },
  {
    id: 19,
    price: 4,
    city: "novi sad",
    img: "./img/objekti/gusanNS.jpg",
    name: "Gusan",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 20,
    price: 4,
    city: "Beograd",
    img: "./img/objekti/samoPivoBG.jpg",
    name: "Samo pivo",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 21,
    price: 4,
    city: "niš",
    img: "./img/objekti/nemirNI.jpg",
    name: "Nemir pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 22,
    price: 31,
    city: "ruma",
    img: "./img/objekti/crni_mata_pub.jpg",
    name: "Dolina Pub",
    info:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 23,
    price: 1,
    city: "ruma",
    img: "./img/objekti/cirkus_pab.jpg",
    name: "Tafaris Pub",
    info:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 24,
    price: 1,
    city: "smederevo",
    img: "./img/objekti/fat_cat.jpg",
    name: "Serbish Pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 25,
    price: 1,
    city: "smederevo",
    img: "./img/objekti/fest.jpg",
    name: "Filigran Caffe",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 26,
    price: 1,
    city: "smederevo",
    img: "./img/objekti/taurunum_pub.jpg",
    name: "The Pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 27,
    price: 1,
    city: "smederevo",
    img: "./img/objekti/lager_pub.jpg",
    name: "Black Dogs Pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 28,
    price: 4,
    city: "Požarevac",
    img: "./img/objekti/office_pub.jpg",
    name: "Barfly Pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 29,
    price: 4,
    city: "Požarevac",
    img: "./img/objekti/gvint.jpg",
    name: "Pub Rock Bulevar",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 30,
    price: 4,
    city: "Valjevo",
    img: "./img/objekti/ciglaBG.jpg",
    name: "Pub 23",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 31,
    price: 4,
    city: "Valjevo",
    img: "./img/objekti/prviMaj.jpg",
    name: "Haustor Pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 32,
    price: 4,
    city: "Obrenovac",
    img: "./img/objekti/zirafaNBG.jpg",
    name: "Jack Union Pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 33,
    price: 4,
    city: "Užice",
    img: "./img/objekti/minisNI.jpg",
    name: "The Dubliner Pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 34,
    price: 4,
    city: "Užice",
    img: "./img/objekti/gvo.jpg",
    name: "Stara užička pivnica",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 35,
    price: 4,
    city: "Užice",
    img: "./img/objekti/samoSU.jpg",
    name: "Caffe Bar Garden",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 36,
    price: 4,
    city: "Kragujevac",
    img: "./img/objekti/livpoolSU.jpg",
    name: "IRISH PUB DEUS",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 37,
    price: 4,
    city: "Kragujevac",
    img: "./img/objekti/beergardenNI.jpg",
    name: "Sputnik 1957",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 38,
    price: 4,
    city: "Kragujevac",
    img: "./img/objekti/gradskaNS.jpg",
    name: "CAFE PUB PRO BONO PUBLICO",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 39,
    price: 4,
    city: "Kragujevac",
    img: "./img/objekti/gusanNS.jpg",
    name: "Dajte Vina Hocu Lom",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 40,
    price: 4,
    city: "Kragujevac",
    img: "./img/objekti/samoPivoBG.jpg",
    name: "Pivnica burence",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 41,
    price: 4,
    city: "Kruševac",
    img: "./img/objekti/nemirNI.jpg",
    name: "Pivnica",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 42,
    price: 31,
    city: "Loznica",
    img: "./img/objekti/crni_mata_pub.jpg",
    name: "IRISH PUB",
    info:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 43,
    price: 1,
    city: "Loznica",
    img: "./img/objekti/cirkus_pab.jpg",
    name: "Beer bar pivnica",
    info:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 44,
    price: 1,
    city: "Loznica",
    img: "./img/objekti/fat_cat.jpg",
    name: "Caffe Bar Torino",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 45,
    price: 4,
    city: "Zrenjanin",
    img: "./img/objekti/beergardenNI.jpg",
    name: "Lion Pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 46,
    price: 4,
    city: "vršac",
    img: "./img/objekti/gradskaNS.jpg",
    name: "Čađava Furuna",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 47,
    price: 4,
    city: "vršac",
    img: "./img/objekti/gusanNS.jpg",
    name: "Wine Pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 48,
    price: 4,
    city: "vršac",
    img: "./img/objekti/samoPivoBG.jpg",
    name: "London Pub",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
  {
    id: 141,
    price: 4,
    city: "vršac",
    img: "./img/objekti/nemirNI.jpg",
    name: "Irish pub Luda krava",
    info:
      "Lorem ipsum tolor sit amet consectetur adipisicing elit. Vel,repellendus!",
    facilities: { petFriendly: true, liveMusic: true, food: false },
  },
];

export const spisakPiva = [
  {
    id: 1,
    name: "Jelen",
    img: "./img/piva/jelen.jpg",
    abv: 4.5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 2,
    name: "Lav",
    img: "./img/piva/lav.jpg",
    abv: 4.5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 3,
    name: "Merak",
    img: "./img/piva/merak.jpg",
    abv: 4.5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 4,
    name: "Zajačarsko",
    img: "./img/piva/zajacarsko.jpg",
    abv: 4.5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 5,
    name: "Nikšićko",
    img: "./img/piva/niksicko.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 6,
    name: "Stella Artois",
    img: "./img/piva/stella.jpg",
    abv: 5.2,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 7,
    name: "Erdinger",
    img: "./img/piva/Erdinger.jpg",
    abv: 5.3,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 8,
    name: "Staropramen",
    img: "./img/piva/Staropramen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 9,
    name: "Kozel",
    img: "./img/piva/Kozel.jpg",
    abv: 4,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 10,
    name: "Tuborg",
    img: "./img/piva/Tuborg.jpg",
    abv: 4.6,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 11,
    name: "Heineken",
    img: "./img/piva/Heineken.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 12,
    name: "Laško",
    img: "./img/piva/Laško.jpg",
    abv: 4.9,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 13,
    name: "Krušovice",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 14,
    name: "Amstel",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 15,
    name: "Grimbergen",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 16,
    name: "Bavaria",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 17,
    name: "Carlsberg",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 18,
    name: "Guinness",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 19,
    name: "Leffe",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 20,
    name: "Konig",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 21,
    name: "Hoegaarden",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 22,
    name: "Dogma",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 23,
    name: "Budweiser",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 24,
    name: "Erdinger",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 25,
    name: "Lowenbrau",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 26,
    name: "Oettinger",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 27,
    name: "Pilsner Urquell",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 28,
    name: "Groish",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 29,
    name: "Paulaner",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 30,
    name: "Kapuziner",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 31,
    name: "Westmalle",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 32,
    name: "Holsten",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
  {
    id: 33,
    name: "San Miquel",
    img: "./img/piva/jelen.jpg",
    abv: 5,
    color: 3,
    gustina: 4,
    oporost: 5,
  },
];
